import React from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import { metrics, profile, weekDays, weekValues, workouts } from './data';
import type { Workout } from './types';

type Screen = 'home' | 'workouts' | 'progress' | 'coach' | 'profile';

const iconFor = (category: string) => category === 'Strength' ? '⚡' : category === 'Core' ? '◎' : category === 'Cardio' ? '↗' : '◌';

function App() {
  const [screen, setScreen] = React.useState<Screen>('home');
  const [selectedWorkout, setSelectedWorkout] = React.useState<Workout | null>(null);
  const [showOnboarding, setShowOnboarding] = React.useState(false);
  if (showOnboarding) return <Onboarding onDone={() => setShowOnboarding(false)} />;
  if (selectedWorkout) return <WorkoutDetail workout={selectedWorkout} onBack={() => setSelectedWorkout(null)} />;
  return <main className="app-shell">
    <header className="topbar"><div><span className="eyebrow">BLACKJACK FITNESS</span><h1>Good morning, {profile.name}.</h1></div><button className="avatar" onClick={() => setScreen('profile')} aria-label="Open profile">A</button></header>
    {screen === 'home' && <Home onWorkout={() => setScreen('workouts')} onSelect={setSelectedWorkout} onCoach={() => setScreen('coach')} />}
    {screen === 'workouts' && <WorkoutsScreen onSelect={setSelectedWorkout} />}
    {screen === 'progress' && <Progress />}
    {screen === 'coach' && <Coach />}
    {screen === 'profile' && <Profile onOnboarding={() => setShowOnboarding(true)} />}
    <nav className="bottom-nav" aria-label="Primary navigation">{([['home','⌂','Home'],['workouts','◉','Workout'],['progress','◒','Progress'],['coach','✦','Coach'],['profile','○','Profile']] as const).map(([id, icon, label]) => <button className={screen === id ? 'nav-item active' : 'nav-item'} key={id} onClick={() => setScreen(id)}><span>{icon}</span>{label}</button>)}</nav>
  </main>;
}

function Home({ onWorkout, onSelect, onCoach }: { onWorkout: () => void; onSelect: (w: Workout) => void; onCoach: () => void }) { return <>
  <section className="hero-card"><div><span className="pill">TODAY'S PLAN</span><h2>Build strength.<br />Move better.</h2><p>Your adaptive plan is ready. Keep your streak alive.</p><button className="primary" onClick={onWorkout}>Start workout <span>→</span></button></div><div className="hero-orbit" aria-hidden="true"><span>BK</span></div></section>
  <Metrics /><section className="section-head"><div><span className="eyebrow">RECOMMENDED</span><h2>Choose your session</h2></div><button className="text-button" onClick={onWorkout}>See all</button></section>
  <section className="workouts">{workouts.slice(0, 3).map(w => <WorkoutCard key={w.id} workout={w} onClick={() => onSelect(w)} />)}</section>
  <button className="coach-banner" onClick={onCoach}><span className="coach-spark">✦</span><span><b>Ask Blackjack Coach</b><small>Get a workout recommendation for today</small></span><strong>›</strong></button>
</>; }
function Metrics() { return <section className="stats-grid"><article><span>STEPS</span><strong>{metrics.steps.toLocaleString()}</strong><small>{Math.round(metrics.steps / metrics.stepGoal * 100)}% of goal</small><div className="progress"><i style={{ width: `${metrics.steps / metrics.stepGoal * 100}%` }} /></div></article><article><span>CALORIES</span><strong>{metrics.calories}</strong><small>kcal active</small><div className="progress"><i style={{ width: '54%' }} /></div></article><article><span>HEART RATE</span><strong>{metrics.heartRate} <em>BPM</em></strong><small>Resting · synced</small><div className="pulse">⌁⌁⌁</div></article></section>; }
function WorkoutCard({ workout, onClick }: { workout: Workout; onClick: () => void }) { return <button className="workout-card" onClick={onClick}><span className="workout-icon">{iconFor(workout.category)}</span><span><b>{workout.title}</b><small>{workout.durationMinutes} min · {workout.level}</small></span><span className="arrow">›</span></button>; }
function WorkoutsScreen({ onSelect }: { onSelect: (w: Workout) => void }) { const [filter, setFilter] = React.useState('All'); const filtered = filter === 'All' ? workouts : workouts.filter(w => w.category === filter); return <><section className="page-heading"><span className="eyebrow">TRAINING LIBRARY</span><h2>Find your next session</h2><p>Choose a workout that matches your energy, time and goal.</p></section><div className="filter-row">{['All','Strength','Cardio','Core','Recovery'].map(x => <button className={filter === x ? 'selected' : ''} key={x} onClick={() => setFilter(x)}>{x}</button>)}</div><section className="workouts">{filtered.map(w => <WorkoutCard key={w.id} workout={w} onClick={() => onSelect(w)} />)}</section></>; }
function WorkoutDetail({ workout, onBack }: { workout: Workout; onBack: () => void }) { const [started, setStarted] = React.useState(false); const [index, setIndex] = React.useState(0); const [seconds, setSeconds] = React.useState(45); React.useEffect(() => { if (!started) return; const timer = window.setInterval(() => setSeconds(s => s <= 1 ? 45 : s - 1), 1000); return () => window.clearInterval(timer); }, [started]); if (started) return <main className="app-shell session-page"><button className="back-button" onClick={() => setStarted(false)}>← Exit session</button><div className="session-progress"><i style={{ width: `${((index + 1) / workout.exercises.length) * 100}%` }} /></div><span className="eyebrow">EXERCISE {index + 1} OF {workout.exercises.length}</span><h1>{workout.exercises[index]}</h1><div className="exercise-visual"><span>{String(seconds).padStart(2, '0')}</span><small>seconds</small></div><p className="session-tip">Keep your movement controlled. Breathe steadily and stop if you feel pain.</p><button className="primary full" onClick={() => index === workout.exercises.length - 1 ? setStarted(false) : (setIndex(index + 1), setSeconds(45))}>{index === workout.exercises.length - 1 ? 'Complete workout ✓' : 'Next exercise →'}</button></main>; return <main className="app-shell detail-page"><button className="back-button" onClick={onBack}>← Back</button><section className="detail-hero"><span className="pill">{workout.category.toUpperCase()}</span><h2>{workout.title}</h2><p>{workout.description}</p><div className="detail-stats"><span>{workout.durationMinutes} min</span><span>{workout.calories} kcal</span><span>{workout.level}</span></div></section><section className="section-head"><div><span className="eyebrow">SESSION</span><h2>{workout.exercises.length} exercises</h2></div></section><div className="exercise-list">{workout.exercises.map((e, i) => <div key={e}><b>{String(i + 1).padStart(2, '0')}</b><span>{e}</span><small>45 sec</small></div>)}</div><button className="primary full" onClick={() => setStarted(true)}>Start this workout →</button></main>; }
function Progress() { return <><section className="page-heading"><span className="eyebrow">YOUR JOURNEY</span><h2>Progress that compounds</h2><p>Small consistent sessions are building your fitness base.</p></section><section className="progress-highlight"><strong>7</strong><span>day streak</span><b>+18%<small> vs last week</small></b></section><section className="chart-card"><div className="chart-values"><b>4</b><span>workouts this week</span></div><div className="bars">{weekValues.map((height, i) => <div className="bar-wrap" key={i}><i style={{ height: `${height}%` }} /><small>{weekDays[i]}</small></div>)}</div></section><section className="stats-grid"><article><span>WEIGHT</span><strong>72.0 <em>KG</em></strong><small>Stable this week</small></article><article><span>WORKOUT TIME</span><strong>86 <em>MIN</em></strong><small>+22 min</small></article><article><span>GOAL</span><strong>68%</strong><small>Strength foundation</small></article></section></>; }
function Coach() { const [messages, setMessages] = React.useState(['Hi! I’m Blackjack Coach. Tell me how much time you have today and I’ll suggest a session.']); const [input, setInput] = React.useState(''); const send = () => { if (!input.trim()) return; const text = input.trim(); setMessages(m => [...m, text, `Based on that, I recommend ${text.toLowerCase().includes('20') ? 'Core & Stability' : 'Full Body Power'}. Start easy, focus on form, and adjust intensity to how you feel.`]); setInput(''); }; return <><section className="page-heading"><span className="eyebrow">AI COACH</span><h2>Train smarter.</h2><p>Personalized guidance based on your goals and recent activity.</p></section><div className="coach-chat">{messages.map((m, i) => <div className={i % 2 === 0 ? 'bubble coach' : 'bubble user'} key={`${m}-${i}`}>{m}</div>)}</div><div className="coach-input"><input value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => e.key === 'Enter' && send()} placeholder="e.g. I have 20 minutes" aria-label="Ask Blackjack Coach" /><button onClick={send}>Send</button></div></>; }
function Profile({ onOnboarding }: { onOnboarding: () => void }) { return <><section className="profile-card"><div className="big-avatar">A</div><span className="eyebrow">YOUR PROFILE</span><h2>{profile.name}</h2><p>{profile.level} · {profile.goal.replace('-', ' ')}</p></section><section className="settings-list">{['Personal information','Fitness goals','Connected devices','Notifications'].map(x => <button key={x}>{x}<span>›</span></button>)}<button onClick={onOnboarding}>Redo onboarding <span>›</span></button></section></>; }
function Onboarding({ onDone }: { onDone: () => void }) { const [step, setStep] = React.useState(0); const steps = [['Welcome to Blackjack','Your personal fitness system for becoming stronger, healthier and more consistent.'],['Know your baseline','We’ll use your height, weight and experience to personalize your plan.'],['Train with intention','Choose goals, follow guided workouts and track your progress over time.']]; return <main className="onboarding"><span className="eyebrow">BLACKJACK FITNESS</span><div className="onboarding-mark">BK</div><span className="pill">STEP {step + 1} OF {steps.length}</span><h1>{steps[step][0]}</h1><p>{steps[step][1]}</p><div className="onboarding-dots">{steps.map((_, i) => <i className={i === step ? 'selected' : ''} key={i} />)}</div><button className="primary full" onClick={() => step === steps.length - 1 ? onDone() : setStep(step + 1)}>{step === steps.length - 1 ? 'Enter Blackjack →' : 'Continue →'}</button></main>; }

createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
